replacement_words = {
    "manger":"manager",
    "supervisor":"manager",
    "bos":"manager",
    "boss":"manager",
    "sup":"manager",
    "mgmt":"management",
    "mgrs":"management",
    "managment":"management",
    "mgr":"manager",
    "superviser":"manager",
    "enviroment":"environment",
    "enviornment":"environment",
    "enviorment":"environment",
    "environement":"environment",
    "plave":"place",
    "env":"environment",
    "envirnment":"environment",
    "envirnoment":"environment",
    "palce":"place",
    "ambiance":"ambience",
    "plce":"place",
    "evironment":"environment",
    "invironment":"environment",
    "envoirnment":"environment",
    "envirment":"environment",
    "atmospher":"atmosphere",
    "cluture":"culture",
    "atmostphere":"atmosphere",
    "atmoshpere":"atmosphere",
    "environmentgood":"environment good",
    "atomosphere":"atmosphere",
    "plae":"place",
    "compnay":"company",
    "funplace":"fun place",
    "enviromment":"environment",
    "palace":"place",
    "envoriment":"environment",
    "envi":"environment",
    "culturegreat":"culture great",
    "envionment":"environment",
    "enironment":"environment",
    "compesation":"compensation",
    "environ":"environment",
    "lace":"place",
    "enviourment":"environment",
    "envirorment":"environment",
    "pleace":"place",
    "atmoshere":"atmosphere",
    "environmen":"environment",
    "opprtunities":"opportunity",
    "environmnet":"environment",
    "workfun":"word fun",
    "opportunitites":"opportunity",
    "opportuinities":"opportunity",
    "experiecne":"experience",
    "oraganization":"organization",
    "oppurtunities":"opportunity",
    "environemnt":"environment",
    "cukture":"culture",
    "culter":"culture",
    "knowedge":"knowledge",
    "vety":"very",
    "workmanagement":"work management",
    "opportunties":"opportunity",
    "athmosphere":"atmosphere",
    "cultutre":"culture",
    "placce":"place",
    "eniviroment":"environment",
    "collagues":"colleagues",
    "oppotunities":"opportunity",
    "workculture":"work culture",
    "companyto":"company",
    "newthings":"new things",
    "culturevery":"culture very",
    "carreer":"career",
    "experiene":"experience",
    "benifts":"benefits",
}