"""empty message

Revision ID: 0af5fdedddff
Revises: 3743d954f653
Create Date: 2020-07-12 16:55:29.785493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af5fdedddff'
down_revision = '3743d954f653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_annotate', sa.Column('created_at', sa.String(length=50), nullable=True))
    op.drop_column('review_annotate', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_annotate', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column('review_annotate', 'created_at')
    # ### end Alembic commands ###
