"""empty message

Revision ID: 3743d954f653
Revises: 88e0080be18e
Create Date: 2020-07-12 16:27:20.301936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3743d954f653'
down_revision = '88e0080be18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_annotate_timestamp', table_name='review_annotate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_review_annotate_timestamp', 'review_annotate', ['timestamp'], unique=False)
    # ### end Alembic commands ###
