"""empty message

Revision ID: 661c2096c391
Revises: c81b49b48f8d
Create Date: 2020-07-12 16:08:50.935778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661c2096c391'
down_revision = 'c81b49b48f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_annotate', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_review_annotate_timestamp'), 'review_annotate', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_annotate_timestamp'), table_name='review_annotate')
    op.drop_column('review_annotate', 'timestamp')
    # ### end Alembic commands ###
