"""empty message

Revision ID: 88e0080be18e
Revises: 661c2096c391
Create Date: 2020-07-12 16:10:01.112799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e0080be18e'
down_revision = '661c2096c391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_annotate', sa.Column('ip', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_annotate', 'ip')
    # ### end Alembic commands ###
