"""empty message

Revision ID: 9a1e3aad7ee6
Revises: 
Create Date: 2020-07-12 15:15:58.405052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1e3aad7ee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('lda_topic_label', sa.Integer(), nullable=True),
    sa.Column('lda_topic_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_index'), 'review', ['index'], unique=True)
    op.create_table('review_annotate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=50), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_annotate')
    op.drop_index(op.f('ix_review_index'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
