"""reviews table

Revision ID: c81b49b48f8d
Revises: 9a1e3aad7ee6
Create Date: 2020-07-12 15:32:48.928707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81b49b48f8d'
down_revision = '9a1e3aad7ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'keywords')
    # ### end Alembic commands ###
