"""empty message

Revision ID: da04c4132133
Revises: 
Create Date: 2020-07-13 08:51:51.020145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da04c4132133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('lda_topic_label', sa.Integer(), nullable=True),
    sa.Column('lda_topic_name', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_index'), 'review', ['index'], unique=True)
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('abae_topic_label', sa.Integer(), nullable=True),
    sa.Column('abae_topic_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_index'), 'sentence', ['index'], unique=False)
    op.create_table('review_annotate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name_primary', sa.Integer(), nullable=True),
    sa.Column('label_name_secondary', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_annotate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name_primary', sa.Integer(), nullable=True),
    sa.Column('label_name_secondary', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_annotate')
    op.drop_table('review_annotate')
    op.drop_index(op.f('ix_sentence_index'), table_name='sentence')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_review_index'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
